# BLC Website Audit - common developer & operator commands.
# Run inside the activated `social-audit` Conda environment (see README / docs/07).
# Usage: `make <target>` (run `make help` for the list).

.DEFAULT_GOAL := help
.PHONY: help install browsers migrate revision \
        run-api run-worker run-frontend \
        test lint format qa qa-repro \
        docker-up docker-down docker-logs docker-migrate clean

help: ## Show available targets
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "} {printf "  \033[36m%-16s\033[0m %s\n", $$1, $$2}'

# --- Setup ------------------------------------------------------------------
install: ## Install Python deps (Poetry) with dev extras
	poetry install --with dev

browsers: ## Install the Playwright Chromium browser used by the crawler
	python -m playwright install chromium chromium-headless-shell

# --- Database ---------------------------------------------------------------
migrate: ## Apply database migrations (alembic upgrade head)
	alembic upgrade head

revision: ## Create a new autogenerated migration: make revision m="message"
	alembic revision --autogenerate -m "$(m)"

# --- Local processes (run each in its own terminal) -------------------------
run-api: ## Start the FastAPI backend on :8000
	uvicorn apps.api.main:app --host 0.0.0.0 --port 8000 --reload

run-worker: ## Start the Celery audit worker
	celery -A apps.worker.celery_app.celery_app worker --loglevel=info

run-frontend: ## Start the Next.js operator UI on :3000
	cd apps/frontend && npm install && npm run dev

# --- Quality ----------------------------------------------------------------
test: ## Run the pytest suite
	pytest

lint: ## Lint with Ruff
	ruff check .

format: ## Format with Ruff
	ruff format .

qa: ## P1-23 local end-to-end QA (pass a fixture name to override the default)
	python scripts/qa_e2e.py $(fixture)

qa-repro: ## P1-24 reproducibility QA (same site twice)
	python scripts/qa_reproducibility.py $(fixture)

# --- Docker Compose stack ---------------------------------------------------
docker-up: ## Build and start the local stack (postgres, redis, api, worker)
	docker compose up --build

docker-down: ## Stop the local stack and remove volumes
	docker compose down -v

docker-logs: ## Tail logs from the local stack
	docker compose logs -f

docker-migrate: ## Run migrations inside the running api container
	docker compose exec api alembic upgrade head

clean: ## Remove Python caches
	find . -type d -name __pycache__ -prune -exec rm -rf {} + 2>/dev/null || true
	find . -type f -name '*.pyc' -delete 2>/dev/null || true
